### ISSUE TITLE
Hovering 

### ISSUE THREAD

**Issue by daqo** [robotika/katarina#1]
I wonder to know what mechanism do you use for hovering. Thank you so much.

**Comment by m3d** [comment]
It is the ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_PCMD, i.e. drone.update(cmd=movePCMDCmd(True, 0,0,0,0)) ... I should add hover() function

**Comment by daqo** [comment]
Thank you. So I guess I just need to do `drone.update(cmd=movePCMDCmd(True, 0,0,0,0))`. Right?
What' the purpose of ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_PCMD?

**Comment by daqo** [comment]
I am working on a C library For Bebop. Everything looks ok but I have problems with hovering.

**Comment by m3d** [comment]
You may try also False for the first parameter. According to ARDrone3 SDK the first flag is "Boolean flag to activate roll/pitch movement", but it is night here so I cannot test it now :(.

**Comment by m3d** [comment]
- can you describe what problem do you have? If it is moving ... do you call trim() at the beginning?

**Comment by daqo** [comment]
Thank you. 
Basically, when I issue my hovering command to the drone, drone execute that with some delay.
Here is my C function for hovering:

```
void ARDrone3SendHoverCommand(DEVICE_MANAGER_t *deviceManager)
{
    deviceManager->dataPCMD.active = 1;
    deviceManager->dataPCMD.roll = 0.0;
    deviceManager->dataPCMD.pitch = 0.0;
    deviceManager->dataPCMD.yaw = 0.0;
    deviceManager->dataPCMD.gaz = 0.0;
    deviceManager->dataPCMD.heading = 0.0;
}
```

**Comment by daqo** [comment]
Yes I do trimming at the beginning.

**Comment by m3d** [comment]
The delay is after takeoff or even if you fly forward, for example? The start takes few seconds and then it turns in hovering state automatically. Do you judge the delay by drone motion or by confirmation of "flying state changed"?

**Comment by daqo** [comment]
So if I fly forward and then issue a hover command, it will take some time for drone to stop.

**Comment by m3d** [comment]
Is it just hover that is delayed or all commands? I.e. isn't it some problem in buffering commands? Can you try this Python version? Same results?

**Comment by daqo** [comment]
@m3d my problem is fixed now. Thank you.

Another question, will drone send us back data after we send it piloting data (such as takeoff, land, pcmd, ...)?

**Comment by m3d** [comment]
OK, let's close this issue and start new one ... with more details. I do not know what do you mean
... the drone is sending data as long as you are confirming ping-pong messages (that was my impression).
