### ISSUE TITLE
Execution issues

### ISSUE THREAD

**Issue by jocacace** [robotika/katarina#4]
Hi guys.

I am really interested to this project because the official sdk is really difficult to understand for me :S. 
I downloaded this project and tryed to execute one sample scritp: "video2stdout.py". Sadly I got this kind of errors:

NameError: global name 'CommandSender' is not defined
NameError: global name 'setSpeedSettingsCmdList' is not defined

Seems that commands.py function are not visible... I am working on Ubuntu 12.04 with python 2.7. Can you help me?

P.s. I have another problem with the test_cvideo.py... I actually don't know what is cvideo. Do you have some suggestions? 

Thank you

**Comment by jocacace** [comment]
Again me.. i don't know why, but changing the name of the source file "commands.py" in another one ( i tryed "Commands.py" with C captical, and modifying the import in bebop.py, the functions in commands source are cognized well. 

Again the errore on cvideo, but I will investigate to solve it.

**Comment by m3d** [comment]
cvideo is C-code from https://github.com/robotika/heidi using CVDrone "installation" for decoding individual video packets. Under Linux it could be problem (see https://github.com/robotika/katarina/issues/3) and I did not try it there.

Regarding CommandSender and setSpeedSettingsCmdList ... both are defined in commands.py ... I am starting the script from directory ... now you added another comment

**Comment by al3Co** [comment]
jocacace, I´m using Unix (Mac OS X) and I had the same problem at the beginning. I solved it installing mplayer. But first try using CVDrone.

**Comment by jocacace** [comment]
Hi m3d and AldoContrego,

Thank you a lot for your reply. Actually i succesfully compiled and installed cvideo on Linux, but I got other execution errors on it. In any case I am searching a way to elaborate the image for a visual servoing algorithms so for me it is not so important to see the image (for example using mplayer) but just to translate in a good format for the elaboration ( like a cv::Mat in OpenCv)... Anyone already done this?

**Comment by jocacace** [comment]
Ok I follow the discussion on  #3 .
