### ISSUE TITLE
WIFI ERROR

### ISSUE THREAD

**Issue by Cubillosxy** [robotika/katarina#8]
hi there

I am programing a code for fly drone with Myo, https://github.com/Cubillosxy/MYO-PYTHON-BEBOP  
i have a problem with the connection Wifi,  this is working if I connect only one devices to the WIfi drone, for example if I connect my phone (only connect, no open app), the program cannot start the connection with my PC.

**Comment by al3Co** [comment]
Hi Cubillosxy...
Download the new version firmware (3.2.0), now you can set a secure wifi connexion between the drone and the device with an 8-characters password (WPA2).
With this only you are going to be connected to the drone and anybody will steal your drone ;)

**Comment by Cubillosxy** [comment]
:+1:  
thanks
